### ISSUE TITLE
Support config file on service generation

### ISSUE THREAD

**Issue by chzhyang** [knative-sandbox/kperf#260]
Kperf users need to specify many flags to generate services, which may brings some inconvenience, such as write mistakes, difficulty in modification, low reusability, etc. 

To improve the usability of kperf, I suggest using a config file(such as yaml) to avoid specifing so many flags. 

I would like to support config file on `kperf generate`, which includes:
- Support both config file and CLI flags
- Change the command to `kperf service generate --config /xxx/config.yaml`
- The proposal config(yaml):
```yaml
service:
  generate:
    number:
    interval:
    batch:
    concurrency:
    min-scale:
    max-scale:
    namespace:
    namespace-prefix:
    namespace-range:
    svc-prefix:
    wait:
    timeout:
    template:
``` 

After the above is successful, I will contributed to support config file on other kperf command.
