### ISSUE TITLE
Support config file on service load

### ISSUE THREAD

**Issue by chzhyang** [knative-sandbox/kperf#267]
Currently, kperf has supported config file on `service generate`(#260 #261 ). While users always need a pipeline during a performance testing(generate->load test...->clean up), to improve the usability, I suggest adding the feature to other subcommands.

To intergate config file into multiple subcommands, we need composing two subcommands into a sample pipeline firstly, I will put efforts in these features:

- [x]  Support config file both on `generate` and `load`
- [x]  Extract common flags to avoid duplicate config file fillings
- [x] `config.yaml` in my ideal likes:
```yaml
service:
  namespace:
  namespace-prefix:
  namespace-range:
  svc-prefix:
  svc-range:
  output:
  generate:
    number:
    interval:
    batch:
    concurrency:
    min-scale:
    max-scale:
    wait:
    timeout:
    template:
  load:
    load-tool:
    load-concurrency:
    load-duration:
```

If the above features are completed, users just need to fill values in config file, then run `kperf service generate`  and `kperf service load`, such sample command! 

After that, we can extend these features to more other subcommands easily.
