### ISSUE TITLE
As a Kperf developer, I want to have a config file to specify the workload instead of add many flags in command line

### ISSUE THREAD

**Issue by zhanggbj** [knative-sandbox/kperf#47]
Adding config file, 

Which may contain

- basic config if any
- workload specification with default values to avoid so many flags
```
kperf service generate -n 30 -b 10 -c 5 -i 15 --namespace-prefix test --namespace-range 1,3 --svc-prefix ktest --max-scale 1 --min-scale 1
```
I would like change to 
```
- service_provision:
  svc_previx: kperf
  min-scale: 1
  xxxx
```

**Comment by zhanggbj** [comment]
Per https://docs.google.com/document/d/1p8Y4CEgAUC4KvVgrSQ5tOH6MZo27nlw-eTQ3tR6Gi2c/edit#heading=h.1i0a5w2u13hj


Add a section for Mako configurations, including

1) Feature flag
Whether to use Mako or not, as public users may not have access to Mako.

2) Mako related configuration.

**Comment by zhanggbj** [comment]
Working in progress. Here is the config proposal.
```
---
kperf:
  log_level: info
svc_provision: 
  total: 1000
  batch: 1
  concurrency: 5
  interval: "10s"
#  namespace: "kperf"
  namespace_prefix: "kperf"
  namespace-range: "1,10"
  svc_prefix: "kperf"
  wait: false
  timeout: "10s"
  max_scale: 1
  min_scale: 0
svc_measure:
  output_dir: "./"
  namespace_prefix: "kperf"
  namespace_range: "1,10"
# namespace: "kperf"

mako:
	enabled: true
```

json format
```
{
  "kperf": {
    "log_level": "info"
  },
  "svc_provision": {
    "total": 1000,
    "batch": 1,
    "concurrency": 5,
    "interval": "10s",
    "namespace_prefix": "kperf",
    "namespace-range": "1,10",
    "svc_prefix": "kperf",
    "wait": false,
    "timeout": "10s",
    "max_scale": 1,
    "min_scale": 0
  },
  "svc_measure": {
    "output_dir": "./",
    "namespace_prefix": "kperf",
    "namespace_range": "1,10"
  },
  "mako": {
    "enabled": true
  }
}
```

Precedence will be

Flags > environment variables > config file > flag defaults
